### ISSUE TITLE
Softlock Problem

### ISSUE THREAD

**Issue by Kithio** [Mayzone/The-Cooker#1]
When having the mod installed and setup and trying to do certain interactions the game locks up and refuses to proceed with the tasks

The fastest one to test on is Tutorial : Stealth - Where the game doesn't open the first door
the other I encountered was Scarface Mansion - it stops doing anything  upon attempting the "Attach Cars to the Magnet" interaction during Stage 2

**Comment by Mayzone** [comment]
Fixed, thank you.
