### ISSUE TITLE
Crash when attempting to load Cook Off 

### ISSUE THREAD

**Issue by Werwolf12** [Mayzone/The-Cooker#2]
'Application has crashed: C++ exception
mods/TheCooker/lab spawn/missionelements.lua:68: attempt to index field 'other' (a nil value)

SCRIPT STACK

init() core/lib/managers/mission/coreelementunitsequence.lua:9
new() core/lib/utils/coreclass.lua:35
_create_elements() core/lib/managers/mission/coremissionmanager.lua:457
init() core/lib/managers/mission/coremissionmanager.lua:403
new() core/lib/utils/coreclass.lua:35
_add_script() core/lib/managers/mission/coremissionmanager.lua:113
_load_mission_file() core/lib/managers/mission/coremissionmanager.lua:107
parse() core/lib/managers/mission/coremissionmanager.lua:78
init_game() lib/setups/gamesetup.lua:725
core/lib/setups/coresetup.lua:422

**Comment by Mayzone** [comment]
Corrupt config file, try to replace it
